FROM instrumentisto/rust:nightly-bullseye-2022-09-24 AS builder
RUN USER=root cargo new --bin ruspie
COPY . /ruspie

WORKDIR /ruspie

COPY ./Cargo.toml ./Cargo.toml
RUN apt-get update && apt-get install -y cmake && cargo +nightly install --locked --git https://github.com/factly/ruspie
FROM debian:bullseye-slim
LABEL org.opencontainers.image.source https://github.com/roapi/roapi

RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
COPY test_data /test_data
COPY --from=builder /usr/local/cargo/bin/roapi /usr/local/bin/roapi

EXPOSE 8080
ENTRYPOINT ["roapi"]
