FROM rust:1.65 as builder

RUN USER=root cargo new --bin ruspie
COPY . /ruspie

WORKDIR /ruspie

COPY ./Cargo.toml ./Cargo.toml
RUN apt-get update && apt-get install -y cmake && cargo build --release

RUN rm ruspie/src/*.rs

ADD . ./

RUN rm ./target/release/deps/ruspie*

FROM debian:buster-slim
ARG APP=/usr/src/app

RUN apt-get update \
  && apt-get install -y ca-certificates tzdata \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

ENV TZ=Etc/UTC \
  APP_USER=appuser

RUN groupadd $APP_USER \
  && useradd -g $APP_USER $APP_USER \
  && mkdir -p ${APP}

COPY --from=builder /ruspie/target/release/ruspie ${APP}/ruspie

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./ruspie"]


