import { NavBar } from '../components/ui/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#F9F9F9] h-screen text-[#1e1e1e]"}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
